class CreateMagento2CatalogProducts < ActiveRecord::Migration[5.0]
  def change
    create_table :magento2_catalog_products do |t|
      t.string :sku
      t.string :store_view_code
      t.string :attribute_set_code
      t.string :product_type
      t.string :categories
      t.string :product_websites
      t.string :name
      t.string :description
      t.string :short_description
      t.string :weight
      t.string :product_online
      t.string :tax_class_name
      t.string :visibility
      t.string :price
      t.string :special_price
      t.string :special_price_from_date
      t.string :special_price_to_date
      t.string :url_key
      t.string :meta_title
      t.string :meta_keywords
      t.string :meta_description
      t.string :base_image
      t.string :base_image_label
      t.string :small_image
      t.string :small_image_label
      t.string :thumbnail_image
      t.string :thumbnail_image_label
      t.string :swatch_image
      t.string :swatch_image_label
      t.string :created_at
      t.string :updated_at
      t.string :new_from_date
      t.string :new_to_date
      t.string :display_product_options_in
      t.string :map_price
      t.string :msrp_price
      t.string :map_enabled
      t.string :gift_message_available
      t.string :custom_design
      t.string :custom_design_from
      t.string :custom_design_to
      t.string :custom_layout_update
      t.string :page_layout
      t.string :product_options_container
      t.string :msrp_display_actual_price_type
      t.string :country_of_manufacture
      t.string :additional_attributes
      t.string :qty
      t.string :out_of_stock_qty
      t.string :use_config_min_qty
      t.string :is_qty_decimal
      t.string :allow_backorders
      t.string :use_config_backorders
      t.string :min_cart_qty
      t.string :use_config_min_sale_qty
      t.string :max_cart_qty
      t.string :use_config_max_sale_qty
      t.string :is_in_stock
      t.string :notify_on_stock_below
      t.string :use_config_notify_stock_qty
      t.string :manage_stock
      t.string :use_config_manage_stock
      t.string :use_config_qty_increments
      t.string :qty_increments
      t.string :use_config_enable_qty_inc
      t.string :enable_qty_increments
      t.string :is_decimal_divided
      t.string :website_id
      t.string :related_skus
      t.string :crosssell_skus
      t.string :upsell_skus
      t.string :additional_images
      t.string :additional_image_labels
      t.string :hide_from_product_page
      t.string :custom_options
      t.string :bundle_price_type
      t.string :bundle_sku_type
      t.string :bundle_price_view
      t.string :bundle_weight_type
      t.string :bundle_values
      t.string :associated_skus
      t.timestamps
    end
  end
end
